version: '3'
services:
  database:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_name
    ports:
      - "3306:3306"
  web:
      container_name: web
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./:/app
        - ./site.conf:/etc/nginx/conf.d/default.conf
      links:
        - php
        - mysql
      depends_on:
        - mysql
  php:
      build:
        dockerfile: ./dockerfiles/Dockerfile
        context: .
      volumes:
        - ./:/app